// Code generated by protoc-gen-go. DO NOT EDIT.
// source: organise.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The means by which the folder is sorted
type Location_Sorting int32

const (
	Location_BY_LABEL_CATNO  Location_Sorting = 0
	Location_BY_DATE_ADDED   Location_Sorting = 1
	Location_BY_RELEASE_DATE Location_Sorting = 2
)

var Location_Sorting_name = map[int32]string{
	0: "BY_LABEL_CATNO",
	1: "BY_DATE_ADDED",
	2: "BY_RELEASE_DATE",
}

var Location_Sorting_value = map[string]int32{
	"BY_LABEL_CATNO":  0,
	"BY_DATE_ADDED":   1,
	"BY_RELEASE_DATE": 2,
}

func (x Location_Sorting) String() string {
	return proto.EnumName(Location_Sorting_name, int32(x))
}

func (Location_Sorting) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fb21ff4bb1a728e0, []int{5, 0}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb21ff4bb1a728e0, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type SortMapping struct {
	InstanceId           int32    `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	EarliestReleaseDate  int64    `protobuf:"varint,2,opt,name=earliest_release_date,json=earliestReleaseDate,proto3" json:"earliest_release_date,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SortMapping) Reset()         { *m = SortMapping{} }
func (m *SortMapping) String() string { return proto.CompactTextString(m) }
func (*SortMapping) ProtoMessage()    {}
func (*SortMapping) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb21ff4bb1a728e0, []int{1}
}

func (m *SortMapping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SortMapping.Unmarshal(m, b)
}
func (m *SortMapping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SortMapping.Marshal(b, m, deterministic)
}
func (m *SortMapping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SortMapping.Merge(m, src)
}
func (m *SortMapping) XXX_Size() int {
	return xxx_messageInfo_SortMapping.Size(m)
}
func (m *SortMapping) XXX_DiscardUnknown() {
	xxx_messageInfo_SortMapping.DiscardUnknown(m)
}

var xxx_messageInfo_SortMapping proto.InternalMessageInfo

func (m *SortMapping) GetInstanceId() int32 {
	if m != nil {
		return m.InstanceId
	}
	return 0
}

func (m *SortMapping) GetEarliestReleaseDate() int64 {
	if m != nil {
		return m.EarliestReleaseDate
	}
	return 0
}

func (m *SortMapping) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type LabelExtractor struct {
	// The id of the label
	LabelId int32 `protobuf:"varint,1,opt,name=label_id,json=labelId,proto3" json:"label_id,omitempty"`
	// The extractor
	Extractor            string   `protobuf:"bytes,2,opt,name=extractor,proto3" json:"extractor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LabelExtractor) Reset()         { *m = LabelExtractor{} }
func (m *LabelExtractor) String() string { return proto.CompactTextString(m) }
func (*LabelExtractor) ProtoMessage()    {}
func (*LabelExtractor) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb21ff4bb1a728e0, []int{2}
}

func (m *LabelExtractor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LabelExtractor.Unmarshal(m, b)
}
func (m *LabelExtractor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LabelExtractor.Marshal(b, m, deterministic)
}
func (m *LabelExtractor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LabelExtractor.Merge(m, src)
}
func (m *LabelExtractor) XXX_Size() int {
	return xxx_messageInfo_LabelExtractor.Size(m)
}
func (m *LabelExtractor) XXX_DiscardUnknown() {
	xxx_messageInfo_LabelExtractor.DiscardUnknown(m)
}

var xxx_messageInfo_LabelExtractor proto.InternalMessageInfo

func (m *LabelExtractor) GetLabelId() int32 {
	if m != nil {
		return m.LabelId
	}
	return 0
}

func (m *LabelExtractor) GetExtractor() string {
	if m != nil {
		return m.Extractor
	}
	return ""
}

type ReleasePlacement struct {
	// The id of the release
	InstanceId int32 `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// The index in the folder
	Index int32 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// The slot in the folder
	Slot int32 `protobuf:"varint,3,opt,name=slot,proto3" json:"slot,omitempty"`
	// The name of this release
	Title                string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReleasePlacement) Reset()         { *m = ReleasePlacement{} }
func (m *ReleasePlacement) String() string { return proto.CompactTextString(m) }
func (*ReleasePlacement) ProtoMessage()    {}
func (*ReleasePlacement) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb21ff4bb1a728e0, []int{3}
}

func (m *ReleasePlacement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReleasePlacement.Unmarshal(m, b)
}
func (m *ReleasePlacement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReleasePlacement.Marshal(b, m, deterministic)
}
func (m *ReleasePlacement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReleasePlacement.Merge(m, src)
}
func (m *ReleasePlacement) XXX_Size() int {
	return xxx_messageInfo_ReleasePlacement.Size(m)
}
func (m *ReleasePlacement) XXX_DiscardUnknown() {
	xxx_messageInfo_ReleasePlacement.DiscardUnknown(m)
}

var xxx_messageInfo_ReleasePlacement proto.InternalMessageInfo

func (m *ReleasePlacement) GetInstanceId() int32 {
	if m != nil {
		return m.InstanceId
	}
	return 0
}

func (m *ReleasePlacement) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ReleasePlacement) GetSlot() int32 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *ReleasePlacement) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type Quota struct {
	// The number of allowed units
	NumOfSlots int32 `protobuf:"varint,1,opt,name=num_of_slots,json=numOfSlots,proto3" json:"num_of_slots,omitempty"`
	// The total width of the set
	TotalWidth int32 `protobuf:"varint,2,opt,name=total_width,json=totalWidth,proto3" json:"total_width,omitempty"`
	// Types that are valid to be assigned to QuotaType:
	//	*Quota_Slots
	//	*Quota_Width
	QuotaType            isQuota_QuotaType `protobuf_oneof:"quota_type"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Quota) Reset()         { *m = Quota{} }
func (m *Quota) String() string { return proto.CompactTextString(m) }
func (*Quota) ProtoMessage()    {}
func (*Quota) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb21ff4bb1a728e0, []int{4}
}

func (m *Quota) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Quota.Unmarshal(m, b)
}
func (m *Quota) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Quota.Marshal(b, m, deterministic)
}
func (m *Quota) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Quota.Merge(m, src)
}
func (m *Quota) XXX_Size() int {
	return xxx_messageInfo_Quota.Size(m)
}
func (m *Quota) XXX_DiscardUnknown() {
	xxx_messageInfo_Quota.DiscardUnknown(m)
}

var xxx_messageInfo_Quota proto.InternalMessageInfo

func (m *Quota) GetNumOfSlots() int32 {
	if m != nil {
		return m.NumOfSlots
	}
	return 0
}

func (m *Quota) GetTotalWidth() int32 {
	if m != nil {
		return m.TotalWidth
	}
	return 0
}

type isQuota_QuotaType interface {
	isQuota_QuotaType()
}

type Quota_Slots struct {
	Slots int32 `protobuf:"varint,3,opt,name=slots,proto3,oneof"`
}

type Quota_Width struct {
	Width int32 `protobuf:"varint,4,opt,name=width,proto3,oneof"`
}

func (*Quota_Slots) isQuota_QuotaType() {}

func (*Quota_Width) isQuota_QuotaType() {}

func (m *Quota) GetQuotaType() isQuota_QuotaType {
	if m != nil {
		return m.QuotaType
	}
	return nil
}

func (m *Quota) GetSlots() int32 {
	if x, ok := m.GetQuotaType().(*Quota_Slots); ok {
		return x.Slots
	}
	return 0
}

func (m *Quota) GetWidth() int32 {
	if x, ok := m.GetQuotaType().(*Quota_Width); ok {
		return x.Width
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Quota) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Quota_OneofMarshaler, _Quota_OneofUnmarshaler, _Quota_OneofSizer, []interface{}{
		(*Quota_Slots)(nil),
		(*Quota_Width)(nil),
	}
}

func _Quota_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Quota)
	// quota_type
	switch x := m.QuotaType.(type) {
	case *Quota_Slots:
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Slots))
	case *Quota_Width:
		b.EncodeVarint(4<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Width))
	case nil:
	default:
		return fmt.Errorf("Quota.QuotaType has unexpected type %T", x)
	}
	return nil
}

func _Quota_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Quota)
	switch tag {
	case 3: // quota_type.slots
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.QuotaType = &Quota_Slots{int32(x)}
		return true, err
	case 4: // quota_type.width
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.QuotaType = &Quota_Width{int32(x)}
		return true, err
	default:
		return false, nil
	}
}

func _Quota_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Quota)
	// quota_type
	switch x := m.QuotaType.(type) {
	case *Quota_Slots:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Slots))
	case *Quota_Width:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Width))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Location struct {
	// The name of the location
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The number of units within the location
	Slots int32 `protobuf:"varint,2,opt,name=slots,proto3" json:"slots,omitempty"`
	// The folder ids that are stored in this location
	FolderIds []int32 `protobuf:"varint,3,rep,packed,name=folder_ids,json=folderIds,proto3" json:"folder_ids,omitempty"`
	// The placement of releases in the folder
	ReleasesLocation []*ReleasePlacement `protobuf:"bytes,4,rep,name=releases_location,json=releasesLocation,proto3" json:"releases_location,omitempty"`
	Sort             Location_Sorting    `protobuf:"varint,5,opt,name=sort,proto3,enum=proto.Location_Sorting" json:"sort,omitempty"`
	// The timestamp of this given location / arrangement
	Timestamp int64 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The allowed quota for this location, if any
	Quota *Quota `protobuf:"bytes,7,opt,name=quota,proto3" json:"quota,omitempty"`
	// The type of format we expect in this location
	ExpectedFormat string `protobuf:"bytes,8,opt,name=expected_format,json=expectedFormat,proto3" json:"expected_format,omitempty"`
	// The type of label we don't expect in this location
	UnexpectedLabel string `protobuf:"bytes,9,opt,name=unexpected_label,json=unexpectedLabel,proto3" json:"unexpected_label,omitempty"`
	// Don't send an alert when there are quota problems
	NoAlert bool `protobuf:"varint,10,opt,name=no_alert,json=noAlert,proto3" json:"no_alert,omitempty"`
	// Folder to move to when this is over quota
	SpillFolder int32 `protobuf:"varint,11,opt,name=spill_folder,json=spillFolder,proto3" json:"spill_folder,omitempty"`
	// Quota Check opt out - if set no alerts on quota
	OptOutQuotaChecks bool `protobuf:"varint,12,opt,name=opt_out_quota_checks,json=optOutQuotaChecks,proto3" json:"opt_out_quota_checks,omitempty"`
	// Time to include reorgs, if < 0 we don't reorg
	ReorgTime            int64    `protobuf:"varint,13,opt,name=reorg_time,json=reorgTime,proto3" json:"reorg_time,omitempty"`
	LastReorg            int64    `protobuf:"varint,14,opt,name=last_reorg,json=lastReorg,proto3" json:"last_reorg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb21ff4bb1a728e0, []int{5}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Location) GetSlots() int32 {
	if m != nil {
		return m.Slots
	}
	return 0
}

func (m *Location) GetFolderIds() []int32 {
	if m != nil {
		return m.FolderIds
	}
	return nil
}

func (m *Location) GetReleasesLocation() []*ReleasePlacement {
	if m != nil {
		return m.ReleasesLocation
	}
	return nil
}

func (m *Location) GetSort() Location_Sorting {
	if m != nil {
		return m.Sort
	}
	return Location_BY_LABEL_CATNO
}

func (m *Location) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Location) GetQuota() *Quota {
	if m != nil {
		return m.Quota
	}
	return nil
}

func (m *Location) GetExpectedFormat() string {
	if m != nil {
		return m.ExpectedFormat
	}
	return ""
}

func (m *Location) GetUnexpectedLabel() string {
	if m != nil {
		return m.UnexpectedLabel
	}
	return ""
}

func (m *Location) GetNoAlert() bool {
	if m != nil {
		return m.NoAlert
	}
	return false
}

func (m *Location) GetSpillFolder() int32 {
	if m != nil {
		return m.SpillFolder
	}
	return 0
}

func (m *Location) GetOptOutQuotaChecks() bool {
	if m != nil {
		return m.OptOutQuotaChecks
	}
	return false
}

func (m *Location) GetReorgTime() int64 {
	if m != nil {
		return m.ReorgTime
	}
	return 0
}

func (m *Location) GetLastReorg() int64 {
	if m != nil {
		return m.LastReorg
	}
	return 0
}

type Organisation struct {
	// Timestamp this organisation was made
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The locations in this sorting
	Locations []*Location `protobuf:"bytes,2,rep,name=locations,proto3" json:"locations,omitempty"`
	// The extractors used for sorting
	Extractors []*LabelExtractor `protobuf:"bytes,3,rep,name=extractors,proto3" json:"extractors,omitempty"`
	// A list of mappings for the releases
	SortMappings         []*SortMapping `protobuf:"bytes,4,rep,name=sort_mappings,json=sortMappings,proto3" json:"sort_mappings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Organisation) Reset()         { *m = Organisation{} }
func (m *Organisation) String() string { return proto.CompactTextString(m) }
func (*Organisation) ProtoMessage()    {}
func (*Organisation) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb21ff4bb1a728e0, []int{6}
}

func (m *Organisation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Organisation.Unmarshal(m, b)
}
func (m *Organisation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Organisation.Marshal(b, m, deterministic)
}
func (m *Organisation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Organisation.Merge(m, src)
}
func (m *Organisation) XXX_Size() int {
	return xxx_messageInfo_Organisation.Size(m)
}
func (m *Organisation) XXX_DiscardUnknown() {
	xxx_messageInfo_Organisation.DiscardUnknown(m)
}

var xxx_messageInfo_Organisation proto.InternalMessageInfo

func (m *Organisation) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Organisation) GetLocations() []*Location {
	if m != nil {
		return m.Locations
	}
	return nil
}

func (m *Organisation) GetExtractors() []*LabelExtractor {
	if m != nil {
		return m.Extractors
	}
	return nil
}

func (m *Organisation) GetSortMappings() []*SortMapping {
	if m != nil {
		return m.SortMappings
	}
	return nil
}

type AddLocationRequest struct {
	Add                  *Location `protobuf:"bytes,1,opt,name=add,proto3" json:"add,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddLocationRequest) Reset()         { *m = AddLocationRequest{} }
func (m *AddLocationRequest) String() string { return proto.CompactTextString(m) }
func (*AddLocationRequest) ProtoMessage()    {}
func (*AddLocationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb21ff4bb1a728e0, []int{7}
}

func (m *AddLocationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddLocationRequest.Unmarshal(m, b)
}
func (m *AddLocationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddLocationRequest.Marshal(b, m, deterministic)
}
func (m *AddLocationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddLocationRequest.Merge(m, src)
}
func (m *AddLocationRequest) XXX_Size() int {
	return xxx_messageInfo_AddLocationRequest.Size(m)
}
func (m *AddLocationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddLocationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddLocationRequest proto.InternalMessageInfo

func (m *AddLocationRequest) GetAdd() *Location {
	if m != nil {
		return m.Add
	}
	return nil
}

type AddLocationResponse struct {
	Now                  *Organisation `protobuf:"bytes,1,opt,name=now,proto3" json:"now,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AddLocationResponse) Reset()         { *m = AddLocationResponse{} }
func (m *AddLocationResponse) String() string { return proto.CompactTextString(m) }
func (*AddLocationResponse) ProtoMessage()    {}
func (*AddLocationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb21ff4bb1a728e0, []int{8}
}

func (m *AddLocationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddLocationResponse.Unmarshal(m, b)
}
func (m *AddLocationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddLocationResponse.Marshal(b, m, deterministic)
}
func (m *AddLocationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddLocationResponse.Merge(m, src)
}
func (m *AddLocationResponse) XXX_Size() int {
	return xxx_messageInfo_AddLocationResponse.Size(m)
}
func (m *AddLocationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddLocationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddLocationResponse proto.InternalMessageInfo

func (m *AddLocationResponse) GetNow() *Organisation {
	if m != nil {
		return m.Now
	}
	return nil
}

type GetOrganisationRequest struct {
	Locations []*Location `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	// Force a reorg on returned locations
	ForceReorg bool `protobuf:"varint,2,opt,name=force_reorg,json=forceReorg,proto3" json:"force_reorg,omitempty"`
	// Reset the reorg time
	OrgReset             bool     `protobuf:"varint,3,opt,name=org_reset,json=orgReset,proto3" json:"org_reset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrganisationRequest) Reset()         { *m = GetOrganisationRequest{} }
func (m *GetOrganisationRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrganisationRequest) ProtoMessage()    {}
func (*GetOrganisationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb21ff4bb1a728e0, []int{9}
}

func (m *GetOrganisationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrganisationRequest.Unmarshal(m, b)
}
func (m *GetOrganisationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrganisationRequest.Marshal(b, m, deterministic)
}
func (m *GetOrganisationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrganisationRequest.Merge(m, src)
}
func (m *GetOrganisationRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrganisationRequest.Size(m)
}
func (m *GetOrganisationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrganisationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrganisationRequest proto.InternalMessageInfo

func (m *GetOrganisationRequest) GetLocations() []*Location {
	if m != nil {
		return m.Locations
	}
	return nil
}

func (m *GetOrganisationRequest) GetForceReorg() bool {
	if m != nil {
		return m.ForceReorg
	}
	return false
}

func (m *GetOrganisationRequest) GetOrgReset() bool {
	if m != nil {
		return m.OrgReset
	}
	return false
}

type GetOrganisationResponse struct {
	Locations            []*Location `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	NumberProcessed      int32       `protobuf:"varint,2,opt,name=number_processed,json=numberProcessed,proto3" json:"number_processed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetOrganisationResponse) Reset()         { *m = GetOrganisationResponse{} }
func (m *GetOrganisationResponse) String() string { return proto.CompactTextString(m) }
func (*GetOrganisationResponse) ProtoMessage()    {}
func (*GetOrganisationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb21ff4bb1a728e0, []int{10}
}

func (m *GetOrganisationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrganisationResponse.Unmarshal(m, b)
}
func (m *GetOrganisationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrganisationResponse.Marshal(b, m, deterministic)
}
func (m *GetOrganisationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrganisationResponse.Merge(m, src)
}
func (m *GetOrganisationResponse) XXX_Size() int {
	return xxx_messageInfo_GetOrganisationResponse.Size(m)
}
func (m *GetOrganisationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrganisationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrganisationResponse proto.InternalMessageInfo

func (m *GetOrganisationResponse) GetLocations() []*Location {
	if m != nil {
		return m.Locations
	}
	return nil
}

func (m *GetOrganisationResponse) GetNumberProcessed() int32 {
	if m != nil {
		return m.NumberProcessed
	}
	return 0
}

type LocateRequest struct {
	InstanceId           int32    `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocateRequest) Reset()         { *m = LocateRequest{} }
func (m *LocateRequest) String() string { return proto.CompactTextString(m) }
func (*LocateRequest) ProtoMessage()    {}
func (*LocateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb21ff4bb1a728e0, []int{11}
}

func (m *LocateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocateRequest.Unmarshal(m, b)
}
func (m *LocateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocateRequest.Marshal(b, m, deterministic)
}
func (m *LocateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocateRequest.Merge(m, src)
}
func (m *LocateRequest) XXX_Size() int {
	return xxx_messageInfo_LocateRequest.Size(m)
}
func (m *LocateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LocateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LocateRequest proto.InternalMessageInfo

func (m *LocateRequest) GetInstanceId() int32 {
	if m != nil {
		return m.InstanceId
	}
	return 0
}

type LocateResponse struct {
	FoundLocation        *Location `protobuf:"bytes,2,opt,name=found_location,json=foundLocation,proto3" json:"found_location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LocateResponse) Reset()         { *m = LocateResponse{} }
func (m *LocateResponse) String() string { return proto.CompactTextString(m) }
func (*LocateResponse) ProtoMessage()    {}
func (*LocateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb21ff4bb1a728e0, []int{12}
}

func (m *LocateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocateResponse.Unmarshal(m, b)
}
func (m *LocateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocateResponse.Marshal(b, m, deterministic)
}
func (m *LocateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocateResponse.Merge(m, src)
}
func (m *LocateResponse) XXX_Size() int {
	return xxx_messageInfo_LocateResponse.Size(m)
}
func (m *LocateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LocateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LocateResponse proto.InternalMessageInfo

func (m *LocateResponse) GetFoundLocation() *Location {
	if m != nil {
		return m.FoundLocation
	}
	return nil
}

type QuotaRequest struct {
	FolderId             int32    `protobuf:"varint,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	IncludeRecords       bool     `protobuf:"varint,2,opt,name=include_records,json=includeRecords,proto3" json:"include_records,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuotaRequest) Reset()         { *m = QuotaRequest{} }
func (m *QuotaRequest) String() string { return proto.CompactTextString(m) }
func (*QuotaRequest) ProtoMessage()    {}
func (*QuotaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb21ff4bb1a728e0, []int{13}
}

func (m *QuotaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuotaRequest.Unmarshal(m, b)
}
func (m *QuotaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuotaRequest.Marshal(b, m, deterministic)
}
func (m *QuotaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuotaRequest.Merge(m, src)
}
func (m *QuotaRequest) XXX_Size() int {
	return xxx_messageInfo_QuotaRequest.Size(m)
}
func (m *QuotaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuotaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuotaRequest proto.InternalMessageInfo

func (m *QuotaRequest) GetFolderId() int32 {
	if m != nil {
		return m.FolderId
	}
	return 0
}

func (m *QuotaRequest) GetIncludeRecords() bool {
	if m != nil {
		return m.IncludeRecords
	}
	return false
}

func (m *QuotaRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type QuotaResponse struct {
	OverQuota            bool     `protobuf:"varint,1,opt,name=over_quota,json=overQuota,proto3" json:"over_quota,omitempty"`
	SpillFolder          int32    `protobuf:"varint,2,opt,name=spill_folder,json=spillFolder,proto3" json:"spill_folder,omitempty"`
	LocationName         string   `protobuf:"bytes,3,opt,name=location_name,json=locationName,proto3" json:"location_name,omitempty"`
	InstanceId           []int32  `protobuf:"varint,4,rep,packed,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Quota                *Quota   `protobuf:"bytes,5,opt,name=quota,proto3" json:"quota,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuotaResponse) Reset()         { *m = QuotaResponse{} }
func (m *QuotaResponse) String() string { return proto.CompactTextString(m) }
func (*QuotaResponse) ProtoMessage()    {}
func (*QuotaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb21ff4bb1a728e0, []int{14}
}

func (m *QuotaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuotaResponse.Unmarshal(m, b)
}
func (m *QuotaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuotaResponse.Marshal(b, m, deterministic)
}
func (m *QuotaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuotaResponse.Merge(m, src)
}
func (m *QuotaResponse) XXX_Size() int {
	return xxx_messageInfo_QuotaResponse.Size(m)
}
func (m *QuotaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuotaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuotaResponse proto.InternalMessageInfo

func (m *QuotaResponse) GetOverQuota() bool {
	if m != nil {
		return m.OverQuota
	}
	return false
}

func (m *QuotaResponse) GetSpillFolder() int32 {
	if m != nil {
		return m.SpillFolder
	}
	return 0
}

func (m *QuotaResponse) GetLocationName() string {
	if m != nil {
		return m.LocationName
	}
	return ""
}

func (m *QuotaResponse) GetInstanceId() []int32 {
	if m != nil {
		return m.InstanceId
	}
	return nil
}

func (m *QuotaResponse) GetQuota() *Quota {
	if m != nil {
		return m.Quota
	}
	return nil
}

type UpdateLocationRequest struct {
	Location             string    `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Update               *Location `protobuf:"bytes,2,opt,name=update,proto3" json:"update,omitempty"`
	DeleteLocation       bool      `protobuf:"varint,3,opt,name=delete_location,json=deleteLocation,proto3" json:"delete_location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateLocationRequest) Reset()         { *m = UpdateLocationRequest{} }
func (m *UpdateLocationRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateLocationRequest) ProtoMessage()    {}
func (*UpdateLocationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb21ff4bb1a728e0, []int{15}
}

func (m *UpdateLocationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateLocationRequest.Unmarshal(m, b)
}
func (m *UpdateLocationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateLocationRequest.Marshal(b, m, deterministic)
}
func (m *UpdateLocationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateLocationRequest.Merge(m, src)
}
func (m *UpdateLocationRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateLocationRequest.Size(m)
}
func (m *UpdateLocationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateLocationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateLocationRequest proto.InternalMessageInfo

func (m *UpdateLocationRequest) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *UpdateLocationRequest) GetUpdate() *Location {
	if m != nil {
		return m.Update
	}
	return nil
}

func (m *UpdateLocationRequest) GetDeleteLocation() bool {
	if m != nil {
		return m.DeleteLocation
	}
	return false
}

type UpdateLocationResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateLocationResponse) Reset()         { *m = UpdateLocationResponse{} }
func (m *UpdateLocationResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateLocationResponse) ProtoMessage()    {}
func (*UpdateLocationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb21ff4bb1a728e0, []int{16}
}

func (m *UpdateLocationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateLocationResponse.Unmarshal(m, b)
}
func (m *UpdateLocationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateLocationResponse.Marshal(b, m, deterministic)
}
func (m *UpdateLocationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateLocationResponse.Merge(m, src)
}
func (m *UpdateLocationResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateLocationResponse.Size(m)
}
func (m *UpdateLocationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateLocationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateLocationResponse proto.InternalMessageInfo

type AddExtractorRequest struct {
	Extractor            *LabelExtractor `protobuf:"bytes,1,opt,name=extractor,proto3" json:"extractor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AddExtractorRequest) Reset()         { *m = AddExtractorRequest{} }
func (m *AddExtractorRequest) String() string { return proto.CompactTextString(m) }
func (*AddExtractorRequest) ProtoMessage()    {}
func (*AddExtractorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb21ff4bb1a728e0, []int{17}
}

func (m *AddExtractorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddExtractorRequest.Unmarshal(m, b)
}
func (m *AddExtractorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddExtractorRequest.Marshal(b, m, deterministic)
}
func (m *AddExtractorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddExtractorRequest.Merge(m, src)
}
func (m *AddExtractorRequest) XXX_Size() int {
	return xxx_messageInfo_AddExtractorRequest.Size(m)
}
func (m *AddExtractorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddExtractorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddExtractorRequest proto.InternalMessageInfo

func (m *AddExtractorRequest) GetExtractor() *LabelExtractor {
	if m != nil {
		return m.Extractor
	}
	return nil
}

type AddExtractorResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddExtractorResponse) Reset()         { *m = AddExtractorResponse{} }
func (m *AddExtractorResponse) String() string { return proto.CompactTextString(m) }
func (*AddExtractorResponse) ProtoMessage()    {}
func (*AddExtractorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb21ff4bb1a728e0, []int{18}
}

func (m *AddExtractorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddExtractorResponse.Unmarshal(m, b)
}
func (m *AddExtractorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddExtractorResponse.Marshal(b, m, deterministic)
}
func (m *AddExtractorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddExtractorResponse.Merge(m, src)
}
func (m *AddExtractorResponse) XXX_Size() int {
	return xxx_messageInfo_AddExtractorResponse.Size(m)
}
func (m *AddExtractorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddExtractorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddExtractorResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("proto.Location_Sorting", Location_Sorting_name, Location_Sorting_value)
	proto.RegisterType((*Empty)(nil), "proto.Empty")
	proto.RegisterType((*SortMapping)(nil), "proto.SortMapping")
	proto.RegisterType((*LabelExtractor)(nil), "proto.LabelExtractor")
	proto.RegisterType((*ReleasePlacement)(nil), "proto.ReleasePlacement")
	proto.RegisterType((*Quota)(nil), "proto.Quota")
	proto.RegisterType((*Location)(nil), "proto.Location")
	proto.RegisterType((*Organisation)(nil), "proto.Organisation")
	proto.RegisterType((*AddLocationRequest)(nil), "proto.AddLocationRequest")
	proto.RegisterType((*AddLocationResponse)(nil), "proto.AddLocationResponse")
	proto.RegisterType((*GetOrganisationRequest)(nil), "proto.GetOrganisationRequest")
	proto.RegisterType((*GetOrganisationResponse)(nil), "proto.GetOrganisationResponse")
	proto.RegisterType((*LocateRequest)(nil), "proto.LocateRequest")
	proto.RegisterType((*LocateResponse)(nil), "proto.LocateResponse")
	proto.RegisterType((*QuotaRequest)(nil), "proto.QuotaRequest")
	proto.RegisterType((*QuotaResponse)(nil), "proto.QuotaResponse")
	proto.RegisterType((*UpdateLocationRequest)(nil), "proto.UpdateLocationRequest")
	proto.RegisterType((*UpdateLocationResponse)(nil), "proto.UpdateLocationResponse")
	proto.RegisterType((*AddExtractorRequest)(nil), "proto.AddExtractorRequest")
	proto.RegisterType((*AddExtractorResponse)(nil), "proto.AddExtractorResponse")
}

func init() { proto.RegisterFile("organise.proto", fileDescriptor_fb21ff4bb1a728e0) }

var fileDescriptor_fb21ff4bb1a728e0 = []byte{
	// 1173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xdd, 0x6e, 0xdb, 0xb6,
	0x17, 0xaf, 0x62, 0x2b, 0xb1, 0x8f, 0x3f, 0xcb, 0x38, 0xa9, 0xea, 0x36, 0xff, 0xfa, 0xaf, 0x61,
	0xa8, 0x8b, 0x61, 0xdd, 0x90, 0x62, 0xeb, 0xcd, 0x6e, 0x9c, 0xda, 0x6d, 0x33, 0x64, 0x4d, 0xc7,
	0x64, 0x18, 0x72, 0x45, 0x28, 0x12, 0xed, 0x08, 0x93, 0x45, 0x95, 0xa4, 0xdb, 0xf4, 0x01, 0x06,
	0xec, 0x9d, 0xb6, 0x37, 0xd8, 0xcd, 0x1e, 0x69, 0xe0, 0x87, 0x64, 0xd9, 0x71, 0x10, 0xec, 0xca,
	0xe6, 0xef, 0xf0, 0x7c, 0x9f, 0xf3, 0xa3, 0xa0, 0xcd, 0xf8, 0x2c, 0x48, 0x63, 0x41, 0x9f, 0x67,
	0x9c, 0x49, 0x86, 0x5c, 0xfd, 0xe3, 0xef, 0x80, 0x3b, 0x99, 0x67, 0xf2, 0xb3, 0x7f, 0x0d, 0x8d,
	0x33, 0xc6, 0xe5, 0x4f, 0x41, 0x96, 0xc5, 0xe9, 0x0c, 0x3d, 0x81, 0x46, 0x9c, 0x0a, 0x19, 0xa4,
	0x21, 0x25, 0x71, 0xe4, 0x39, 0x03, 0x67, 0xe8, 0x62, 0xc8, 0xa1, 0xe3, 0x08, 0x1d, 0xc2, 0x1e,
	0x0d, 0x78, 0x12, 0x53, 0x21, 0x09, 0xa7, 0x09, 0x0d, 0x04, 0x25, 0x51, 0x20, 0xa9, 0xb7, 0x35,
	0x70, 0x86, 0x15, 0xbc, 0x9b, 0x0b, 0xb1, 0x91, 0x8d, 0x03, 0x49, 0x51, 0x0f, 0x5c, 0x19, 0xcb,
	0x84, 0x7a, 0x95, 0x81, 0x33, 0xac, 0x63, 0x73, 0xf0, 0x8f, 0xa1, 0x7d, 0x12, 0x5c, 0xd2, 0x64,
	0x72, 0x2d, 0x79, 0x10, 0x4a, 0xc6, 0xd1, 0x43, 0xa8, 0x25, 0x0a, 0x59, 0x7a, 0xde, 0xd1, 0xe7,
	0xe3, 0x08, 0x3d, 0x86, 0x3a, 0xcd, 0xef, 0x69, 0x57, 0x75, 0xbc, 0x04, 0x7c, 0x01, 0x5d, 0xeb,
	0xef, 0x7d, 0x12, 0x84, 0x74, 0x4e, 0x53, 0x79, 0x77, 0x26, 0x3d, 0x70, 0xe3, 0x34, 0xa2, 0xd7,
	0xda, 0x9c, 0x8b, 0xcd, 0x01, 0x21, 0xa8, 0x8a, 0x84, 0x49, 0x1d, 0xaa, 0x8b, 0xf5, 0xff, 0x65,
	0xfc, 0xd5, 0x72, 0xfc, 0x7f, 0x38, 0xe0, 0xfe, 0xbc, 0x60, 0x32, 0x40, 0x03, 0x68, 0xa6, 0x8b,
	0x39, 0x61, 0x53, 0xa2, 0xae, 0x8b, 0xdc, 0x57, 0xba, 0x98, 0x9f, 0x4e, 0xcf, 0x14, 0xa2, 0x82,
	0x91, 0x4c, 0x06, 0x09, 0xf9, 0x14, 0x47, 0xf2, 0xca, 0x7a, 0x04, 0x0d, 0xfd, 0xaa, 0x10, 0xb4,
	0x0f, 0xae, 0xd1, 0xd5, 0x7e, 0xdf, 0xde, 0xc3, 0xe6, 0xa8, 0x70, 0xa3, 0x52, 0xcd, 0x71, 0x7d,
	0x3c, 0x6a, 0x02, 0x7c, 0x50, 0xbe, 0x89, 0xfc, 0x9c, 0x51, 0xff, 0x9f, 0x2a, 0xd4, 0x4e, 0x58,
	0x18, 0xc8, 0x98, 0xa5, 0x2a, 0x83, 0x34, 0x98, 0x53, 0x1d, 0x45, 0x1d, 0xeb, 0xff, 0x2a, 0x03,
	0x63, 0xde, 0xe6, 0x6a, 0x8c, 0x1f, 0x00, 0x4c, 0x59, 0x12, 0x51, 0x4e, 0xe2, 0x48, 0x79, 0xae,
	0x0c, 0x5d, 0x5c, 0x37, 0xc8, 0x71, 0x24, 0xd0, 0x18, 0xee, 0xdb, 0x0e, 0x0b, 0x92, 0x58, 0xeb,
	0x5e, 0x75, 0x50, 0x19, 0x36, 0x0e, 0x1f, 0x98, 0x69, 0x7a, 0xbe, 0x5e, 0x75, 0xdc, 0xcd, 0x35,
	0x8a, 0x70, 0xbe, 0x82, 0xaa, 0x60, 0x5c, 0x7a, 0xee, 0xc0, 0x19, 0xb6, 0x0b, 0xc5, 0x5c, 0xfc,
	0x5c, 0x0d, 0x5f, 0x9c, 0xce, 0xb0, 0xbe, 0xa4, 0xda, 0x2c, 0xe3, 0x39, 0x15, 0x32, 0x98, 0x67,
	0xde, 0xb6, 0x9e, 0xa8, 0x25, 0x80, 0x7c, 0x70, 0x75, 0xd2, 0xde, 0xce, 0xc0, 0x19, 0x36, 0x0e,
	0x9b, 0xd6, 0x96, 0x6e, 0x02, 0x36, 0x22, 0xf4, 0x14, 0x3a, 0xf4, 0x3a, 0xa3, 0xa1, 0xa4, 0x11,
	0x99, 0x32, 0x3e, 0x0f, 0xa4, 0x57, 0xd3, 0x85, 0x68, 0xe7, 0xf0, 0x6b, 0x8d, 0xa2, 0x67, 0xd0,
	0x5d, 0xa4, 0xc5, 0x55, 0x3d, 0x67, 0x5e, 0x5d, 0xdf, 0xec, 0x2c, 0x71, 0x3d, 0xa0, 0x6a, 0x2e,
	0x53, 0x46, 0x82, 0x84, 0x72, 0xe9, 0xc1, 0xc0, 0x19, 0xd6, 0xf0, 0x4e, 0xca, 0x46, 0xea, 0x88,
	0xfe, 0x0f, 0x4d, 0x91, 0xc5, 0x49, 0x42, 0x4c, 0xd9, 0xbc, 0x86, 0xae, 0x6f, 0x43, 0x63, 0xaf,
	0x35, 0x84, 0xbe, 0x81, 0x1e, 0xcb, 0x24, 0x61, 0x0b, 0x49, 0x4c, 0xcb, 0xc2, 0x2b, 0x1a, 0xfe,
	0x26, 0xbc, 0xa6, 0xb6, 0x74, 0x9f, 0x65, 0xf2, 0x74, 0x21, 0x75, 0x0e, 0xaf, 0xb4, 0x40, 0xb5,
	0x85, 0x53, 0xc6, 0x67, 0x44, 0x65, 0xee, 0xb5, 0x4c, 0x15, 0x34, 0x72, 0x1e, 0xcf, 0xa9, 0x12,
	0x27, 0x81, 0xde, 0x3e, 0xc6, 0x67, 0x5e, 0xdb, 0x88, 0x15, 0x82, 0x15, 0xe0, 0x4f, 0x60, 0xc7,
	0xd6, 0x14, 0x21, 0x68, 0x1f, 0x5d, 0x90, 0x93, 0xd1, 0xd1, 0xe4, 0x84, 0xbc, 0x1a, 0x9d, 0xbf,
	0x3b, 0xed, 0xde, 0x43, 0xf7, 0xa1, 0x75, 0x74, 0x41, 0xc6, 0xa3, 0xf3, 0x09, 0x19, 0x8d, 0xc7,
	0x93, 0x71, 0xd7, 0x41, 0xbb, 0xd0, 0x39, 0xba, 0x20, 0x78, 0x72, 0x32, 0x19, 0x9d, 0x4d, 0xb4,
	0xa8, 0xbb, 0xe5, 0xff, 0xed, 0x40, 0xf3, 0xd4, 0x50, 0x87, 0xe9, 0xe3, 0x4a, 0x6b, 0x9c, 0xf5,
	0xd6, 0x7c, 0x0d, 0xf5, 0x7c, 0x44, 0xd4, 0x90, 0xa9, 0x19, 0xe9, 0xac, 0xb5, 0x1a, 0x2f, 0x6f,
	0xa0, 0xef, 0x00, 0x8a, 0xed, 0x35, 0x93, 0xd7, 0x38, 0xdc, 0xcb, 0xef, 0xaf, 0x90, 0x02, 0x2e,
	0x5d, 0x44, 0x2f, 0xa1, 0xa5, 0xc6, 0x84, 0xcc, 0x0d, 0x5b, 0x09, 0x3b, 0x8d, 0xc8, 0x6a, 0x96,
	0x88, 0x0c, 0x37, 0xc5, 0xf2, 0x20, 0xfc, 0x97, 0x80, 0x46, 0x51, 0x54, 0x44, 0x42, 0x3f, 0x2c,
	0xa8, 0x50, 0xcd, 0xab, 0x04, 0x91, 0xa1, 0x86, 0x0d, 0xe1, 0x2a, 0x99, 0xff, 0x03, 0xec, 0xae,
	0x28, 0x8a, 0x8c, 0xa5, 0x82, 0xa2, 0x2f, 0xa1, 0x92, 0xb2, 0x4f, 0x56, 0x73, 0xd7, 0x6a, 0x96,
	0xcb, 0x85, 0x95, 0xdc, 0xff, 0xdd, 0x81, 0xfd, 0x37, 0x54, 0xae, 0x08, 0xac, 0xef, 0x95, 0x82,
	0x39, 0x77, 0x16, 0xec, 0x09, 0x34, 0xa6, 0x8c, 0x87, 0xd4, 0x76, 0x7d, 0x4b, 0xcf, 0x0e, 0x68,
	0x48, 0xb7, 0x1d, 0x3d, 0x82, 0xba, 0x1a, 0x19, 0x4e, 0x05, 0x35, 0xe4, 0x55, 0xc3, 0x35, 0xc6,
	0x67, 0x58, 0x9d, 0x7d, 0x01, 0x0f, 0x6e, 0x84, 0x61, 0x33, 0xf9, 0x8f, 0x71, 0x3c, 0x83, 0x6e,
	0xba, 0x98, 0x5f, 0x52, 0x4e, 0x32, 0xce, 0x42, 0x2a, 0x04, 0x8d, 0x2c, 0xa7, 0x74, 0x0c, 0xfe,
	0x3e, 0x87, 0xfd, 0x6f, 0xa1, 0xa5, 0x2d, 0xd0, 0x3c, 0xe5, 0xbb, 0x18, 0xd9, 0x7f, 0x0b, 0xed,
	0x5c, 0xc3, 0x46, 0xf7, 0x3d, 0xb4, 0xa7, 0x6c, 0x91, 0x46, 0x4b, 0xfe, 0xd9, 0xda, 0xdc, 0xac,
	0x96, 0xbe, 0x96, 0x1f, 0xfd, 0x2b, 0x68, 0x1a, 0x56, 0xb0, 0xae, 0x1f, 0x41, 0xbd, 0x60, 0x3a,
	0xeb, 0xb8, 0x96, 0x13, 0x9d, 0xa2, 0x8c, 0x38, 0x0d, 0x93, 0x45, 0xa4, 0xaa, 0x1b, 0x32, 0x1e,
	0x09, 0x5b, 0xdf, 0xb6, 0x85, 0xb1, 0x41, 0x0b, 0x66, 0xad, 0x2c, 0x99, 0xd5, 0xff, 0xd3, 0x81,
	0x96, 0x75, 0x65, 0x63, 0x3e, 0x00, 0x60, 0x1f, 0x29, 0x37, 0xcb, 0xae, 0x9d, 0xd5, 0x70, 0x5d,
	0x21, 0xe6, 0xb1, 0x58, 0x67, 0x8c, 0xad, 0x9b, 0x8c, 0xf1, 0x05, 0xb4, 0xf2, 0x7c, 0x49, 0xc9,
	0x61, 0x33, 0x07, 0xdf, 0x29, 0x4a, 0x5f, 0xab, 0x66, 0x55, 0xb3, 0x77, 0xf9, 0x7d, 0x2b, 0xd8,
	0xd2, 0xbd, 0x95, 0x2d, 0xd5, 0x80, 0xee, 0xfd, 0x92, 0xa9, 0xf7, 0x7b, 0x7d, 0x37, 0xfa, 0x50,
	0x2b, 0x6a, 0x6e, 0x5e, 0x92, 0xe2, 0x8c, 0x9e, 0xc2, 0xf6, 0x22, 0x2b, 0x1e, 0xfd, 0x0d, 0xdd,
	0xb0, 0x62, 0x55, 0xd9, 0x88, 0x26, 0x54, 0xd2, 0x65, 0xff, 0xcc, 0x68, 0xb6, 0x0d, 0x5c, 0xf4,
	0xcb, 0x83, 0xfd, 0xf5, 0x30, 0x4c, 0x35, 0xfd, 0x1f, 0xf5, 0x02, 0x2e, 0xe9, 0xc0, 0x86, 0xf7,
	0xa2, 0xfc, 0x3d, 0x60, 0xd6, 0xf0, 0x16, 0xfe, 0x28, 0x7d, 0x26, 0xec, 0x43, 0x6f, 0xd5, 0x96,
	0xf1, 0x71, 0xf8, 0x57, 0x05, 0xba, 0x76, 0x39, 0x28, 0x3f, 0xa3, 0xfc, 0x63, 0x1c, 0x52, 0xf4,
	0x1a, 0x1a, 0xa5, 0xcd, 0x47, 0x0f, 0xad, 0xf5, 0x9b, 0x34, 0xd2, 0xef, 0x6f, 0x12, 0xd9, 0xf0,
	0xef, 0x21, 0x0c, 0x9d, 0xb5, 0xdd, 0x43, 0x07, 0x56, 0x61, 0x33, 0x35, 0xf4, 0xff, 0x77, 0x9b,
	0xb8, 0xb0, 0x79, 0x0a, 0xed, 0xd5, 0x72, 0xa1, 0xc7, 0x56, 0x67, 0x63, 0x33, 0xfb, 0x07, 0xb7,
	0x48, 0x0b, 0x83, 0x2f, 0x61, 0xdb, 0x6c, 0x1e, 0xea, 0x95, 0x7b, 0x99, 0xaf, 0x6e, 0x7f, 0x6f,
	0x0d, 0x2d, 0x29, 0xd6, 0xde, 0x50, 0xf3, 0x7a, 0xa1, 0xdd, 0x95, 0x09, 0xb3, 0x9a, 0xbd, 0x55,
	0xb0, 0x50, 0x3c, 0x86, 0x66, 0xb9, 0x17, 0xa8, 0x54, 0xc4, 0xf5, 0x66, 0xf7, 0x1f, 0x6d, 0x94,
	0xe5, 0xa6, 0x2e, 0xb7, 0xb5, 0xf4, 0xc5, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xec, 0x87, 0x66,
	0xe3, 0xeb, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrganiserServiceClient is the client API for OrganiserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrganiserServiceClient interface {
	AddLocation(ctx context.Context, in *AddLocationRequest, opts ...grpc.CallOption) (*AddLocationResponse, error)
	GetOrganisation(ctx context.Context, in *GetOrganisationRequest, opts ...grpc.CallOption) (*GetOrganisationResponse, error)
	UpdateLocation(ctx context.Context, in *UpdateLocationRequest, opts ...grpc.CallOption) (*UpdateLocationResponse, error)
	Locate(ctx context.Context, in *LocateRequest, opts ...grpc.CallOption) (*LocateResponse, error)
	GetQuota(ctx context.Context, in *QuotaRequest, opts ...grpc.CallOption) (*QuotaResponse, error)
	AddExtractor(ctx context.Context, in *AddExtractorRequest, opts ...grpc.CallOption) (*AddExtractorResponse, error)
}

type organiserServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrganiserServiceClient(cc *grpc.ClientConn) OrganiserServiceClient {
	return &organiserServiceClient{cc}
}

func (c *organiserServiceClient) AddLocation(ctx context.Context, in *AddLocationRequest, opts ...grpc.CallOption) (*AddLocationResponse, error) {
	out := new(AddLocationResponse)
	err := c.cc.Invoke(ctx, "/proto.OrganiserService/AddLocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organiserServiceClient) GetOrganisation(ctx context.Context, in *GetOrganisationRequest, opts ...grpc.CallOption) (*GetOrganisationResponse, error) {
	out := new(GetOrganisationResponse)
	err := c.cc.Invoke(ctx, "/proto.OrganiserService/GetOrganisation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organiserServiceClient) UpdateLocation(ctx context.Context, in *UpdateLocationRequest, opts ...grpc.CallOption) (*UpdateLocationResponse, error) {
	out := new(UpdateLocationResponse)
	err := c.cc.Invoke(ctx, "/proto.OrganiserService/UpdateLocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organiserServiceClient) Locate(ctx context.Context, in *LocateRequest, opts ...grpc.CallOption) (*LocateResponse, error) {
	out := new(LocateResponse)
	err := c.cc.Invoke(ctx, "/proto.OrganiserService/Locate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organiserServiceClient) GetQuota(ctx context.Context, in *QuotaRequest, opts ...grpc.CallOption) (*QuotaResponse, error) {
	out := new(QuotaResponse)
	err := c.cc.Invoke(ctx, "/proto.OrganiserService/GetQuota", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organiserServiceClient) AddExtractor(ctx context.Context, in *AddExtractorRequest, opts ...grpc.CallOption) (*AddExtractorResponse, error) {
	out := new(AddExtractorResponse)
	err := c.cc.Invoke(ctx, "/proto.OrganiserService/AddExtractor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrganiserServiceServer is the server API for OrganiserService service.
type OrganiserServiceServer interface {
	AddLocation(context.Context, *AddLocationRequest) (*AddLocationResponse, error)
	GetOrganisation(context.Context, *GetOrganisationRequest) (*GetOrganisationResponse, error)
	UpdateLocation(context.Context, *UpdateLocationRequest) (*UpdateLocationResponse, error)
	Locate(context.Context, *LocateRequest) (*LocateResponse, error)
	GetQuota(context.Context, *QuotaRequest) (*QuotaResponse, error)
	AddExtractor(context.Context, *AddExtractorRequest) (*AddExtractorResponse, error)
}

func RegisterOrganiserServiceServer(s *grpc.Server, srv OrganiserServiceServer) {
	s.RegisterService(&_OrganiserService_serviceDesc, srv)
}

func _OrganiserService_AddLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganiserServiceServer).AddLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OrganiserService/AddLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganiserServiceServer).AddLocation(ctx, req.(*AddLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganiserService_GetOrganisation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrganisationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganiserServiceServer).GetOrganisation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OrganiserService/GetOrganisation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganiserServiceServer).GetOrganisation(ctx, req.(*GetOrganisationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganiserService_UpdateLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganiserServiceServer).UpdateLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OrganiserService/UpdateLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganiserServiceServer).UpdateLocation(ctx, req.(*UpdateLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganiserService_Locate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganiserServiceServer).Locate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OrganiserService/Locate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganiserServiceServer).Locate(ctx, req.(*LocateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganiserService_GetQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganiserServiceServer).GetQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OrganiserService/GetQuota",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganiserServiceServer).GetQuota(ctx, req.(*QuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganiserService_AddExtractor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddExtractorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganiserServiceServer).AddExtractor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OrganiserService/AddExtractor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganiserServiceServer).AddExtractor(ctx, req.(*AddExtractorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrganiserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.OrganiserService",
	HandlerType: (*OrganiserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddLocation",
			Handler:    _OrganiserService_AddLocation_Handler,
		},
		{
			MethodName: "GetOrganisation",
			Handler:    _OrganiserService_GetOrganisation_Handler,
		},
		{
			MethodName: "UpdateLocation",
			Handler:    _OrganiserService_UpdateLocation_Handler,
		},
		{
			MethodName: "Locate",
			Handler:    _OrganiserService_Locate_Handler,
		},
		{
			MethodName: "GetQuota",
			Handler:    _OrganiserService_GetQuota_Handler,
		},
		{
			MethodName: "AddExtractor",
			Handler:    _OrganiserService_AddExtractor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "organise.proto",
}
